/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import allfungsi.Analisisdata;
import allfungsi.Hasil_analisis;
import allfungsi.Semuadata;
import allfungsi.prosescrud;
import loginnew.login;

/**
 *
 * @author Rahimsyah
 */
public class form_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form form_dashboard
     */
    prosescrud ps = new prosescrud();
    Analisisdata as = new Analisisdata();
    Hasil_analisis hs = new Hasil_analisis();
    Semuadata ss = new Semuadata();

    public form_dashboard() {
        initComponents();
        comboall();
        tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form_hasilanalisis = new javax.swing.JButton();
        form_dashboard = new javax.swing.JButton();
        form_inputdata = new javax.swing.JButton();
        form_lihatdata = new javax.swing.JButton();
        form_analisis = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_lihatdata = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_analisis = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_hasilanalisis = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btn_inputdata2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_dashboard = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtrtrw = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jcbpekerjaan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbsbt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbslt = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbsumper = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbsumair = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcbsumenergi = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jcbstatmas = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jcbjumtang = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jcbterbansos = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jcbjenpen = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        btn_saveinputdata = new javax.swing.JButton();
        btn_updateinputdata = new javax.swing.JButton();
        btn_hapusinputdata = new javax.swing.JButton();
        btn_kosongkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Jrtrwinputdata = new javax.swing.JComboBox<>();
        btn_refresh = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jcbrtrwanalisis = new javax.swing.JComboBox<>();
        btn_proses = new javax.swing.JButton();
        btn_saveanalisis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelanalisisdata = new javax.swing.JTable();
        tittleanalisis = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_hasil = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jcb_hasilanalisis = new javax.swing.JComboBox<>();
        btn_cetakhasil = new javax.swing.JButton();
        btn_layak = new javax.swing.JButton();
        btn_tidaklayak = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_semua = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jcb_perrt = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 103, 170, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_user_54px.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 40));

        form_hasilanalisis.setForeground(new java.awt.Color(255, 255, 255));
        form_hasilanalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_leaderboard_24px.png"))); // NOI18N
        form_hasilanalisis.setText("HASIL ANALISIS");
        form_hasilanalisis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        form_hasilanalisis.setContentAreaFilled(false);
        form_hasilanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_hasilanalisisActionPerformed(evt);
            }
        });
        jPanel1.add(form_hasilanalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, -1));

        form_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        form_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_dashboard_layout_24px_1.png"))); // NOI18N
        form_dashboard.setText("DASHBOARD");
        form_dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        form_dashboard.setContentAreaFilled(false);
        form_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(form_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, -1));

        form_inputdata.setForeground(new java.awt.Color(255, 255, 255));
        form_inputdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_input_24px.png"))); // NOI18N
        form_inputdata.setText("INPUT DATA");
        form_inputdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        form_inputdata.setContentAreaFilled(false);
        form_inputdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_inputdataActionPerformed(evt);
            }
        });
        jPanel1.add(form_inputdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, -1));

        form_lihatdata.setForeground(new java.awt.Color(255, 255, 255));
        form_lihatdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_data_recovery_24px.png"))); // NOI18N
        form_lihatdata.setText("SEMUA DATA");
        form_lihatdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        form_lihatdata.setContentAreaFilled(false);
        form_lihatdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_lihatdataActionPerformed(evt);
            }
        });
        jPanel1.add(form_lihatdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, -1));

        form_analisis.setForeground(new java.awt.Color(255, 255, 255));
        form_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_process_24px.png"))); // NOI18N
        form_analisis.setText("ANALISIS DATA");
        form_analisis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        form_analisis.setContentAreaFilled(false);
        form_analisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_analisisActionPerformed(evt);
            }
        });
        jPanel1.add(form_analisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jButton10.setText("HOME");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 590));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tittle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_tittle.setForeground(new java.awt.Color(255, 255, 255));
        txt_tittle.setText("DASHBOARD");
        jPanel3.add(txt_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 290, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_user_30px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 12, -1, 31));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 930, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_lihatdata.setBackground(new java.awt.Color(102, 255, 255));
        btn_lihatdata.setForeground(new java.awt.Color(255, 255, 255));
        btn_lihatdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_data_recovery_64px_1.png"))); // NOI18N
        btn_lihatdata.setText("LIHAT DATA");
        btn_lihatdata.setBorderPainted(false);
        btn_lihatdata.setContentAreaFilled(false);
        btn_lihatdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihatdataActionPerformed(evt);
            }
        });
        jPanel4.add(btn_lihatdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 90));

        jPanel6.setBackground(new java.awt.Color(51, 204, 0));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_analisis.setBackground(new java.awt.Color(102, 255, 255));
        btn_analisis.setForeground(new java.awt.Color(255, 255, 255));
        btn_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_process_64px_2.png"))); // NOI18N
        btn_analisis.setText("ANALISIS DATA");
        btn_analisis.setBorderPainted(false);
        btn_analisis.setContentAreaFilled(false);
        btn_analisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analisisActionPerformed(evt);
            }
        });
        jPanel6.add(btn_analisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(102, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_data_recovery_64px_1.png"))); // NOI18N
        jButton5.setText("INPUT DATA");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, 90));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 190, 90));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_hasilanalisis.setBackground(new java.awt.Color(102, 255, 255));
        btn_hasilanalisis.setForeground(new java.awt.Color(255, 255, 255));
        btn_hasilanalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_leaderboard_64px_1.png"))); // NOI18N
        btn_hasilanalisis.setText("HASIL");
        btn_hasilanalisis.setBorderPainted(false);
        btn_hasilanalisis.setContentAreaFilled(false);
        btn_hasilanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hasilanalisisActionPerformed(evt);
            }
        });
        jPanel9.add(btn_hasilanalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 190, 90));

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inputdata2.setBackground(new java.awt.Color(102, 255, 255));
        btn_inputdata2.setForeground(new java.awt.Color(255, 255, 255));
        btn_inputdata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminform/Icon/icons8_input_64px.png"))); // NOI18N
        btn_inputdata2.setText("INPUT DATA");
        btn_inputdata2.setBorderPainted(false);
        btn_inputdata2.setContentAreaFilled(false);
        btn_inputdata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputdata2ActionPerformed(evt);
            }
        });
        jPanel11.add(btn_inputdata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 90));

        tb_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb_dashboard);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 890, 330));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("DATA MASYARAKAT");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTabbedPane1.addTab("DASHBOARD", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("ID");

        jLabel6.setText("Nama");

        jLabel20.setText("RT/RW");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtrtrw, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrtrw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)))
        );

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 30));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jcbpekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel7.setText("PEKERJAAN");

        jcbsbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel8.setText("STATUS BANGUNAN TINGGAL");

        jcbslt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel9.setText("STATUS LAHAN TINGGAL");

        jLabel10.setText("SUMBER PENERANGAN");

        jcbsumper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel11.setText("SUMBER AIR MINUM");

        jcbsumair.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel12.setText("SUMBER ENERGI MASAK");

        jcbsumenergi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel13.setText("STATUS MASYARAKAT");

        jcbstatmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel14.setText("JUMLAH TANGGUNGAN");

        jcbjumtang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbpekerjaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbsbt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jcbslt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbsumper, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbsumair, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbsumenergi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbstatmas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jcbjumtang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbsbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbslt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbsumper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbsumair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbsumenergi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbstatmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbjumtang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 440));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jcbterbansos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel15.setText("TERKAIT BANSOS LAIN");

        jcbjenpen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        jLabel16.setText("JENJANG PENDIDIKAN");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbterbansos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jcbjenpen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbterbansos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbjenpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 120));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        btn_saveinputdata.setText("SIMPAN");
        btn_saveinputdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveinputdataActionPerformed(evt);
            }
        });

        btn_updateinputdata.setText("PERBAHARUI");
        btn_updateinputdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateinputdataActionPerformed(evt);
            }
        });

        btn_hapusinputdata.setText("HAPUS");
        btn_hapusinputdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusinputdataActionPerformed(evt);
            }
        });

        btn_kosongkan.setText("KOSONGKAN");
        btn_kosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kosongkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_saveinputdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_updateinputdata, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(btn_hapusinputdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_kosongkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(btn_saveinputdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_updateinputdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapusinputdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kosongkan)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 520, -1));

        Jrtrwinputdata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "001/001", "002/002", "003/003", "004/004", "005/005" }));
        Jrtrwinputdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrtrwinputdataActionPerformed(evt);
            }
        });
        jPanel8.add(Jrtrwinputdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 60, 90, -1));

        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel8.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jLabel21.setText("RT/RW");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        jTabbedPane1.addTab("INPUTDATA", jPanel8);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("RT/RW");

        jcbrtrwanalisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "001/001", "002/002", "003/003", "004/004", "005/005" }));
        jcbrtrwanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbrtrwanalisisActionPerformed(evt);
            }
        });

        btn_proses.setText("PROSES");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_saveanalisis.setText("SIMPAN");
        btn_saveanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveanalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbrtrwanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(btn_proses, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_saveanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jcbrtrwanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proses)
                    .addComponent(btn_saveanalisis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelanalisisdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelanalisisdata);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tittleanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(tittleanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ANALISIS DATA", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        tabel_hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel_hasil);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("RT/RW");

        jcb_hasilanalisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "001/001", "002/002", "003/003", "004/004", "005/005" }));
        jcb_hasilanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_hasilanalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_hasilanalisis, 0, 188, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jcb_hasilanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btn_cetakhasil.setText("CETAK");
        btn_cetakhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakhasilActionPerformed(evt);
            }
        });

        btn_layak.setText("Layak");
        btn_layak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_layakActionPerformed(evt);
            }
        });

        btn_tidaklayak.setText("Tidak layak");
        btn_tidaklayak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tidaklayakActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cetakhasil)
                        .addGap(285, 285, 285))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_layak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_tidaklayak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_layak)
                        .addGap(21, 21, 21)
                        .addComponent(btn_tidaklayak))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cetakhasil)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HASIL", jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        tabel_semua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabel_semua);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("RT/RW");

        jcb_perrt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "001/001", "002/002", "003/003", "004/004", "005/005" }));
        jcb_perrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_perrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_perrt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jcb_perrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton9.setText("CETAK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LIHAT DATA", jPanel14);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 930, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//======================================================================================bagian luarr//
    private void form_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_dashboardActionPerformed
        txt_tittle.setText("DASHBOARD");
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_form_dashboardActionPerformed

    private void form_inputdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_inputdataActionPerformed
        txt_tittle.setText("INPUT DATA");
        jTabbedPane1.setSelectedIndex(1);
        Jrtrwinputdata.setSelectedIndex(0);
        tabel();
        ps.semuatextfield(txtid, txtnama, txtrtrw);
        ps.semuacombo(jcbpekerjaan, jcbsbt, jcbslt, jcbsumper, jcbsumair, jcbsumenergi, jcbstatmas, jcbjumtang, jcbjenpen, jcbterbansos);
    }//GEN-LAST:event_form_inputdataActionPerformed

    private void form_lihatdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_lihatdataActionPerformed
        txt_tittle.setText("SEMUA DATA");
        jTabbedPane1.setSelectedIndex(4);
        jcb_perrt.setSelectedIndex(0);
        ss.Tampilsemuadata(tabel_semua);
        ss.Ukurancolom(tabel_semua);
    }//GEN-LAST:event_form_lihatdataActionPerformed

    private void form_analisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_analisisActionPerformed
        txt_tittle.setText("ANALISI DATA");
        jTabbedPane1.setSelectedIndex(2);
        jcbrtrwanalisis.setSelectedIndex(0);
        as.tampilsemuadata(tabelanalisisdata);
    }//GEN-LAST:event_form_analisisActionPerformed

    private void form_hasilanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_hasilanalisisActionPerformed
        txt_tittle.setText("HASIL ANALISIS");
        jTabbedPane1.setSelectedIndex(3);
        jcb_hasilanalisis.setSelectedIndex(0);
    }//GEN-LAST:event_form_hasilanalisisActionPerformed
//=========================================================================================================//
//=====================================================================================INPUT DATA===============//
    private void btn_inputdata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputdata2ActionPerformed
        txt_tittle.setText("INPUT DATA");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_inputdata2ActionPerformed

    private void btn_lihatdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihatdataActionPerformed
        txt_tittle.setText("LIHAT DATA");
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btn_lihatdataActionPerformed

    private void btn_analisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analisisActionPerformed
        txt_tittle.setText("ANALISI DATA");
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_analisisActionPerformed

    private void btn_hasilanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hasilanalisisActionPerformed
        txt_tittle.setText("HASIL");
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btn_hasilanalisisActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        ps.Ambildatatabel(jTable1, evt, txtid, txtnama, txtrtrw, jcbpekerjaan, jcbsbt, jcbslt, jcbsumper, jcbsumair, jcbsumenergi, jcbstatmas, jcbjumtang, jcbjenpen, jcbterbansos);
    }//GEN-LAST:event_jTable1MouseClicked

    private void JrtrwinputdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrtrwinputdataActionPerformed
        String ambil = (String) Jrtrwinputdata.getSelectedItem();
        ps.Tampildatart(jTable1, ambil);
        ps.Ukurancolom(jTable1);
    }//GEN-LAST:event_JrtrwinputdataActionPerformed

    private void btn_saveinputdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveinputdataActionPerformed
        ps.insertdata(txtnama.getText(), txtrtrw.getText(), jcbpekerjaan.getSelectedIndex(), jcbsbt.getSelectedIndex(), jcbslt.getSelectedIndex(), jcbsumper.getSelectedIndex(), jcbsumair.getSelectedIndex(), jcbsumenergi.getSelectedIndex(), jcbstatmas.getSelectedIndex(), jcbjumtang.getSelectedIndex(), jcbjenpen.getSelectedIndex(), jcbterbansos.getSelectedIndex());
        tabel();
        ps.semuatextfield(txtid, txtnama, txtrtrw);
        ps.semuacombo(jcbpekerjaan, jcbsbt, jcbslt, jcbsumper, jcbsumair, jcbsumenergi, jcbstatmas, jcbjumtang, jcbjenpen, jcbterbansos);
 
    }//GEN-LAST:event_btn_saveinputdataActionPerformed

    private void btn_updateinputdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateinputdataActionPerformed
        ps.Updatedata(txtnama.getText(), txtrtrw.getText(), jcbpekerjaan.getSelectedIndex(), jcbsbt.getSelectedIndex(), jcbslt.getSelectedIndex(), jcbsumper.getSelectedIndex(), jcbsumair.getSelectedIndex(), jcbsumenergi.getSelectedIndex(), jcbstatmas.getSelectedIndex(), jcbjumtang.getSelectedIndex(), jcbjenpen.getSelectedIndex(), jcbterbansos.getSelectedIndex(), txtid.getText());
        tabel();
    }//GEN-LAST:event_btn_updateinputdataActionPerformed

    private void btn_hapusinputdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusinputdataActionPerformed
        ps.Deletedata(txtid.getText());
        tabel();
    }//GEN-LAST:event_btn_hapusinputdataActionPerformed

    private void btn_kosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kosongkanActionPerformed
        ps.Kosongkandata();
        tabel();
    }//GEN-LAST:event_btn_kosongkanActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        ps.semuatextfield(txtid, txtnama, txtrtrw);
        ps.semuacombo(jcbpekerjaan, jcbsbt, jcbslt, jcbsumper, jcbsumair, jcbsumenergi, jcbstatmas, jcbjumtang, jcbjenpen, jcbterbansos);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void comboall() {
        ps.Pilihan(jcbpekerjaan, "tb_pekerjaan");
        ps.Pilihan(jcbsbt, "tb_sbtinggal");
        ps.Pilihan(jcbslt, "tb_sltinggal");
        ps.Pilihan(jcbsumper, "tb_sumper");
        ps.Pilihan(jcbsumair, "tb_sumair");
        ps.Pilihan(jcbsumenergi, "tb_energimasak");
        ps.Pilihan(jcbstatmas, "tb_stm");
        ps.Pilihan(jcbjumtang, "tb_jumt");
        ps.Pilihan(jcbterbansos, "tb_terbansos");
        ps.Pilihan(jcbjenpen, "tb_jenjangpendidikan");
    }

    private void tabel() {
        ps.Tampildata(jTable1);
        ps.Ukurancolom(jTable1);
        as.tampilsemuadata(tabelanalisisdata);
        ss.Tampilsemuadata(tabel_semua);
        ss.Tampilsemuadata(tb_dashboard);
        ss.Ukurancolom(tabel_semua);
        ss.Ukurancolom(tb_dashboard);
    }
    //======================================================================================================= FORM ANALISIS DATA//     

    private void jcbrtrwanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbrtrwanalisisActionPerformed
        as.perubahanbutton(jcbrtrwanalisis, tabelanalisisdata, tittleanalisis, btn_saveanalisis);
        if (jcbrtrwanalisis.getSelectedItem().equals("Pilih")) {
            btn_saveanalisis.setText("SIMPAN");
            tittleanalisis.setText("");
        }
    }//GEN-LAST:event_jcbrtrwanalisisActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        as.hasilnetfow(tabelanalisisdata, jcbrtrwanalisis);
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_saveanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveanalisisActionPerformed
        as.savedata(jcbrtrwanalisis, btn_saveanalisis);
    }//GEN-LAST:event_btn_saveanalisisActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        loginnew.login lg = new login();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed
//==============================================================================Form hasil analisis===============================//
    private void btn_cetakhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakhasilActionPerformed
        hs.Cetak(jcb_hasilanalisis);
    }//GEN-LAST:event_btn_cetakhasilActionPerformed

    private void jcb_hasilanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_hasilanalisisActionPerformed
        hs.Tampildata(jcb_hasilanalisis, tabel_hasil);
    }//GEN-LAST:event_jcb_hasilanalisisActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ss.cetakdata();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jcb_perrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_perrtActionPerformed
        ss.TampilPerrt(tabel_semua, jcb_perrt);
        ss.Ukurancolom(tabel_semua);
    }//GEN-LAST:event_jcb_perrtActionPerformed

    private void btn_layakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_layakActionPerformed
        as.ambildatalayak(jcb_hasilanalisis, jLabel23, tabel_hasil);
    }//GEN-LAST:event_btn_layakActionPerformed

    private void btn_tidaklayakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tidaklayakActionPerformed
        as.ambildatatidaklayak(jcb_hasilanalisis, jLabel23, tabel_hasil);
    }//GEN-LAST:event_btn_tidaklayakActionPerformed
//=========================================================================================================================//

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jrtrwinputdata;
    private javax.swing.JButton btn_analisis;
    private javax.swing.JButton btn_cetakhasil;
    private javax.swing.JButton btn_hapusinputdata;
    private javax.swing.JButton btn_hasilanalisis;
    private javax.swing.JButton btn_inputdata2;
    private javax.swing.JButton btn_kosongkan;
    private javax.swing.JButton btn_layak;
    private javax.swing.JButton btn_lihatdata;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_saveanalisis;
    private javax.swing.JButton btn_saveinputdata;
    private javax.swing.JButton btn_tidaklayak;
    private javax.swing.JButton btn_updateinputdata;
    private javax.swing.JButton form_analisis;
    private javax.swing.JButton form_dashboard;
    private javax.swing.JButton form_hasilanalisis;
    private javax.swing.JButton form_inputdata;
    private javax.swing.JButton form_lihatdata;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcb_hasilanalisis;
    private javax.swing.JComboBox<String> jcb_perrt;
    private javax.swing.JComboBox<String> jcbjenpen;
    private javax.swing.JComboBox<String> jcbjumtang;
    private javax.swing.JComboBox<String> jcbpekerjaan;
    private javax.swing.JComboBox<String> jcbrtrwanalisis;
    private javax.swing.JComboBox<String> jcbsbt;
    private javax.swing.JComboBox<String> jcbslt;
    private javax.swing.JComboBox<String> jcbstatmas;
    private javax.swing.JComboBox<String> jcbsumair;
    private javax.swing.JComboBox<String> jcbsumenergi;
    private javax.swing.JComboBox<String> jcbsumper;
    private javax.swing.JComboBox<String> jcbterbansos;
    private javax.swing.JTable tabel_hasil;
    private javax.swing.JTable tabel_semua;
    private javax.swing.JTable tabelanalisisdata;
    private javax.swing.JTable tb_dashboard;
    private javax.swing.JLabel tittleanalisis;
    private javax.swing.JLabel txt_tittle;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtrtrw;
    // End of variables declaration//GEN-END:variables
}
